# Generated by Django 2.1.7 on 2019-03-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctptrade',
            name='Account',
            field=models.ForeignKey(default='simnow_dev', on_delete=django.db.models.deletion.CASCADE, to='api.CTPAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Account',
            field=models.ForeignKey(default='simnow_dev', on_delete=django.db.models.deletion.CASCADE, to='api.CTPAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctporder',
            name='FrontID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
