# Generated by Django 2.1.7 on 2019-03-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190323_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctporder',
            name='Account',
            field=models.ForeignKey(default='simnow_dev', on_delete=django.db.models.deletion.CASCADE, to='api.CTPAccount'),
            preserve_default=False,
        ),
    ]
