# Generated by Django 2.1.5 on 2019-01-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarPeriod',
            fields=[
                ('period', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
