# Generated by Django 2.1.7 on 2019-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190414_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctpaccount',
            name='AppID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctpaccount',
            name='AuthCode',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
