# Generated by Django 2.1.7 on 2019-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ctporder_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Finished',
        ),
        migrations.AddField(
            model_name='order',
            name='CancelTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
