# Generated by Django 2.1.7 on 2019-08-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190728_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='UnderlyingInstrID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
