# Generated by Django 2.1.5 on 2019-01-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('InstrumentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ExchangeID', models.CharField(max_length=20)),
                ('InstrumentName', models.CharField(max_length=20)),
                ('ExchangeInstID', models.CharField(max_length=20)),
                ('ProductID', models.CharField(max_length=20)),
                ('ProductClass', models.CharField(max_length=20)),
                ('DeliveryYear', models.IntegerField()),
                ('DeliveryMonth', models.IntegerField()),
                ('MaxMarketOrderVolume', models.IntegerField()),
                ('MinMarketOrderVolume', models.IntegerField()),
                ('MaxLimitOrderVolume', models.IntegerField()),
                ('MinLimitOrderVolume', models.IntegerField()),
                ('VolumeMultiple', models.IntegerField()),
                ('PriceTick', models.DecimalField(decimal_places=3, max_digits=20)),
                ('CreateDate', models.CharField(max_length=20)),
                ('OpenDate', models.CharField(max_length=20)),
                ('ExpireDate', models.CharField(max_length=20)),
                ('StartDelivDate', models.CharField(max_length=20)),
                ('EndDelivDate', models.CharField(max_length=20)),
                ('InstLifePhase', models.CharField(max_length=20)),
                ('IsTrading', models.IntegerField()),
                ('PositionType', models.CharField(max_length=20)),
                ('PositionDateType', models.CharField(max_length=20)),
                ('LongMarginRatio', models.DecimalField(decimal_places=3, max_digits=20)),
                ('ShortMarginRatio', models.DecimalField(decimal_places=3, max_digits=20)),
                ('MaxMarginSideAlgorithm', models.CharField(max_length=20)),
                ('UnderlyingInstrID', models.CharField(max_length=20)),
                ('StrikePrice', models.FloatField()),
                ('OptionsType', models.CharField(max_length=20)),
                ('UnderlyingMultiple', models.DecimalField(decimal_places=3, max_digits=20)),
                ('CombinationType', models.CharField(max_length=20)),
            ],
        ),
    ]
