# Generated by Django 2.1.7 on 2019-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190328_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='StatusMsg',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ctporder',
            name='CancelTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctporder',
            name='CompleteTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='CancelTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='CompleteTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
