# Generated by Django 2.1.7 on 2019-08-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190809_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctptrade',
            name='Account',
        ),
        migrations.AddField(
            model_name='ctptrade',
            name='Direction',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctptrade',
            name='Instrument',
            field=models.ForeignKey(default='IC1908', on_delete=django.db.models.deletion.CASCADE, to='api.Instrument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctptrade',
            name='OffsetFlag',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctporder',
            name='InstrumentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Instrument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='InstrumentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Instrument'),
        ),
    ]
