version: 1
formatters:
  simple:
    format: '%(asctime)s [%(filename)s:%(lineno)d(%(funcName)s)] [%(levelname)s] - %(message)s'
handlers:
  default:
    class: 'logging.StreamHandler'
    level: 'DEBUG'
    formatter: 'simple'
    stream: 'ext://sys.stdout'
  file:
    class: 'logging.handlers.RotatingFileHandler'
    level: 'INFO'
    formatter: 'simple'
    filename: 'logs/trade.log'
root:
  handlers:
    - default
    - file
  level: 'INFO'
  propagate: False